// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenVpnPilot.Data;

#nullable disable

namespace OpenVpnPilot.Data.Migrations
{
    [DbContext(typeof(PilotDbContext))]
    partial class PilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.CredentialSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresOneTimeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CredentialSets");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.HotkeyBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gesture")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .IsUnique();

                    b.ToTable("HotkeyBindings");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CredentialSetId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FavouriteSlot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUnsupportedOptions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelfContained")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastConnectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ProtectRoutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemotePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresCredentials")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CredentialSetId");

                    b.HasIndex("FavouriteSlot")
                        .IsUnique()
                        .HasFilter("[FavouriteSlot] IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.ProfileTag", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProfileTags");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AveragePingMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDetail")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalAddress")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StartedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.SessionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Profile", b =>
                {
                    b.HasOne("OpenVpnPilot.Data.Entities.CredentialSet", "CredentialSet")
                        .WithMany("Profiles")
                        .HasForeignKey("CredentialSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CredentialSet");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.ProfileTag", b =>
                {
                    b.HasOne("OpenVpnPilot.Data.Entities.Profile", "Profile")
                        .WithMany("Tags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenVpnPilot.Data.Entities.Tag", "Tag")
                        .WithMany("Profiles")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Session", b =>
                {
                    b.HasOne("OpenVpnPilot.Data.Entities.Profile", "Profile")
                        .WithMany("Sessions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.SessionEvent", b =>
                {
                    b.HasOne("OpenVpnPilot.Data.Entities.Session", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.CredentialSet", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Profile", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Session", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("OpenVpnPilot.Data.Entities.Tag", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
