#!/bin/sh
# Starts one of the ten servers, or the material generator.
#
# The server number is the only thing a container is told. Everything else about it comes from the
# shared description, so a server and the client configuration written for it cannot drift apart.

set -eu

if [ "${1:-}" = "generate" ]; then
    exec /usr/local/bin/generate.sh
fi

. /lab/servers.sh

index="${LAB_INDEX:?LAB_INDEX must name which of the ten servers this is}"
describe_server "$index"

name=$(printf 'server-%02d' "$index")
PKI="/pki"
CONFIG="/etc/openvpn/server.conf"

while [ ! -f "$PKI/.complete" ]; do
    echo "Waiting for the certificate material"
    sleep 2
done

mkdir -p /etc/openvpn /dev/net

# Docker maps the device in, but a container that starts before the daemon has done so needs the
# node to exist for OpenVPN to open it.
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
    chmod 600 /dev/net/tun
fi

{
    echo "# Generated by the lab entrypoint. Server $index: $LAB_SUMMARY"
    echo "port 1194"
    echo "proto $LAB_PROTO"
    echo "dev tun"
    echo "topology subnet"
    echo "server $LAB_TUNNEL 255.255.255.0"
    echo "keepalive 10 60"
    echo "persist-key"
    echo "persist-tun"
    echo "verb 3"
    echo "dh none"

    # No Diffie Hellman file: the certificates are elliptic curve, so the key exchange is ECDHE.
    echo "ca $PKI/ca.crt"
    echo "cert $PKI/$name.crt"
    echo "key $PKI/$name.key"
    echo "tls-crypt $PKI/tls-crypt.key"

    echo "$LAB_PUSH_SITE"

    case "$LAB_AUTH" in
        *userpass*)
            # via-env keeps the values out of the filesystem. The script decides what is acceptable,
            # including the two kinds of one time code.
            echo "script-security 3"
            echo "auth-user-pass-verify /usr/local/bin/verify-credentials.sh via-env"

            # OpenVPN builds a fresh environment for a script rather than passing its own on, so
            # the server number has to be put there explicitly. Without it the script cannot tell
            # which server it is answering for, and every server behaves like the plainest one.
            echo "setenv LAB_INDEX $index"
            echo "username-as-common-name"
            ;;
    esac

    if [ -n "$LAB_SERVER_EXTRA" ]; then
        echo "$LAB_SERVER_EXTRA"
    fi
} > "$CONFIG"

echo "Server $index: $LAB_SUMMARY"
echo "  tunnel $LAB_TUNNEL/24, site $LAB_SITE, $LAB_PROTO, authentication $LAB_AUTH"

# A tunnel that reaches the site behind it needs this container to route and to translate. Without
# the translation the site would answer to a tunnel address it has no route back to.
#
# Compose sets the forwarding switch when the container is created. Setting it again covers a
# container started without that, and there is nothing to do when it is already right.
if [ "$(cat /proc/sys/net/ipv4/ip_forward)" != "1" ]; then
    sysctl -w net.ipv4.ip_forward=1 > /dev/null
fi

iptables -t nat -C POSTROUTING -s "$LAB_TUNNEL/24" -j MASQUERADE 2> /dev/null \
    || iptables -t nat -A POSTROUTING -s "$LAB_TUNNEL/24" -j MASQUERADE

# The one time code servers keep their state where the verification script can find it.
mkdir -p /run/lab

exec openvpn --config "$CONFIG"
